Filter and report generation
SondreUM/gen-ai pull request #15
Opened 2024-05-02 16:29 UTC by frapzo

Added features:

* multi-threaded crawling for better performance using multiprocessing.Pool
* modified identity of crawler to bypass most filters
* wikipedia search
* filter for collected web pages
* report generation by cross referencing filtered web pages

2024-05-02 16:35 UTC, frapzo commented
Example of resulting report when searching for microsoft:

[report.md](https://github.com/SondreUM/gen-ai/files/15191235/report.md)

2024-05-03 12:20 UTC, stiansolli approved these changes
lgtm, nicely done!

2024-05-03 16:39 UTC, frapzo commented
some bugs were discovered with excessively large lines when running the filter. so will close down the pull request until it's fixed

2024-05-05 21:34 UTC, frapzo commented
filter will also save anything rejected by Azure content filter to a review directory for manual review

2024-05-06 13:23 UTC, stiansolli requested changes
See comments.

2024-05-06 13:23 UTC, stiansolli commented on src/processing.py
> +    response = get(f"https://api.wikimedia.org/core/v1/wikipedia/en/search/title?q={modified_query}&limit=1")
Should probably utilize the same gpt rankings scheme as the google search on wikipedia, having only the top result may lead to wrong results. As in the case of searching for UiT, the top result from this is UiTM United Football Club...

2024-05-06 13:23 UTC, stiansolli commented on src/filter.py
> +                        to_read = len(new_line) if len(new_line) // 4 < 3000 else 3000*4
Why else 3000*4 and not 3000 as before?

2024-05-06 13:23 UTC, stiansolli commented on src/filter.py
> +                    gpt_response = use_gpt(data, organization, file)
I think getting GPT to summarize with slicing this way may yield some weird results, however I know that this is an edgecase based on the token limit of gpt.

2024-05-06 16:18 UTC, frapzo commented on src/filter.py
> +                        to_read = len(new_line) if len(new_line) // 4 < 3000 else 3000*4
to_read is specifically how many characters to read. Not how many tokens to read. as such 3000*4 means that we read 3000 tokens

2024-05-06 16:23 UTC, frapzo commented on src/filter.py
> +                    gpt_response = use_gpt(data, organization, file)
This is a compromise that will essentially always exist as long as the model used is one with a token limit. It sucks, but that is just reality. with gpt we are also limited by the token limit of the reponses, so even if the input token limit was eliminated one would want to slice it up due to response limit.

2024-05-06 19:27 UTC, merged